import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>DK's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Darker+Grotesque&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.mainPageAlign}>

        <Image
          className={styles.bgWrap}
          alt="Starfield"
          src="/background.jpeg"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: 'cover',
          }}
        />

        <h1 className={styles.mainHeading}>Desmand King's Portfolio</h1>

        <div className={styles.mainContentAlign}>
          <p>Hello, boozhoo, aanii, my name is Desmand King. Creation drives me,
            design and its endless possibilities excite me, and innovation never ceases to astound me.
            I’m dedicated to three key disciplines: design principles, software development, and Agile
            leadership. As a certified Scrum Master, I believe in the Scrum Framework and its
            possibilities for innovation in the workplace. My Anishinabek heritage and teachings
            connect me to the beauty and potential in all things. Designing, capturing, and creating
            digital experiences is now what drives me.</p>
          <Image
            alt="Profile photo"
            src="/dk-img.jpg"
            width={600}
            height={400}
          />
        </div>

        <div className={styles.mainSubHeading}>
          <h2>Multi-Talented Creative Technologist</h2>
          <h3>Skills for your business</h3>
        </div>

        <div className={styles.flipAlign}>
          <div className={styles.flipCard}>
            <div className={styles.flipCardInner}>
              <div className={styles.flipCardFront}>
                <h1>Creative Design</h1>
              </div>
              <div className={styles.flipCardBack}>
                <h3>Creative Design</h3>
                <p>Are you looking for an inclusive creative design
                  for your business? Implementing accessibility and
                  empowering users is my paramount motivation.</p>
              </div>
            </div>
          </div>

          <div className={styles.flipCard}>
            <div className={styles.flipCardInner}>
              <div className={styles.flipCardFront}>
                <h1>Front-End Development</h1>
              </div>
              <div className={styles.flipCardBack}>
                <h3>Front-End Development</h3>
                <p>Do you need help building  a responsive website?
                  Problem solving using HTML5, CSS3, and Javascript
                  tools is what I provide. </p>
              </div>
            </div>
          </div>

          <div className={styles.flipCard}>
            <div className={styles.flipCardInner}>
              <div className={styles.flipCardFront}>
                <h1>Project Mangement</h1>
              </div>
              <div className={styles.flipCardBack}>
                <h3>Project Mangement</h3>
                <p>Is your project in need of enthusiastic leadership?
                  Agile team facilitation with cross functional teams
                  is what really drives me.</p>
              </div>
            </div>
          </div>
        </div>

        <h2>A selection of my front end apps</h2>

        <div className={styles.mainButtonsCont}>
          <h3>Let's check the weather in your city!</h3>
          <h3>Click the button below</h3>
          <Link href='/weather'>
            <button className={styles.buttonStyle}>Weather</button>
          </Link>
        </div>

        <div className={styles.mainButtonsCont}>
          <h3>Expo Line Map Demo</h3>
          <Link href='/map'>
            <button className={styles.buttonStyle}>Map</button>
          </Link>
        </div>

        <div className={styles.ctaContainer}>
          <h2>Let's work together</h2>
          <p>Are you looking for a creative technologist to help
            you with your next project? I'd love to hear from you.</p>
          <Link href='https://blackskydesignstudio.com/contact/'>
            <button className={styles.buttonStyle}>Contact Me</button>
          </Link>
        </div>

      </main>
    </>
  )
}
