import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Map from '../Map'

export default function Home() {
  return (
    <>
      <Head>
        <title>DK's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mapPageAlign}>
        <Image
          className={styles.bgWrap}
          alt="Starfield"
          src="/background.jpeg"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: 'cover',
          }}
        />

        <Map />

        <Link href='/'>
          <button className={styles.buttonStyle}>Back</button>
        </Link>

      </main>
    </>
  )
}
