import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react';
import axios from 'axios';

export default function Home() {

  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState('');
  const [error, setErrorMessage] = useState('');
  const [data, setData] = useState({});

  var apiKey = process.env.NEXT_PUBLIC_API_KEY;;
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;


  const searchLocation = (event) => {
    if (event.key === "Enter") {
      axios.get(url)
        .then((response) => {
          console.clear();
          setData(response.data)
          console.log(response.data);
          setWeather(response.data.weather);
          setErrorMessage("");
        }).catch(err => {
          console.log(err);
          setErrorMessage("Enter another location")
          setData({});
          setWeather();
        })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>DK's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Darker+Grotesque&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.mainWeatherContainer}>
        <Image
          className={styles.bgWrap}
          alt="Starfield"
          src="/background.jpeg"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: 'cover',
          }}
        />

        <div className={styles.weatherContainer}>

          <h1 style={{ fontSize: 46 }}>Your quick weather app!</h1>
          {
            weather && weather.map((w, index) => {
              return (
                <h2 style={{ fontSize: 36 }}>Location:</h2>
              )
            })
          }
          <h2 style={{ fontSize: 36 }}>{data.name}</h2>
          <input
            className={styles.inputStyle}
            value={location}
            onChange={event => setLocation(event.target.value)}
            placeholder="Enter Location"
            onKeyDown={searchLocation}
            type="text"
          />
          <h3>Enter Your Location</h3>

          {
            weather && weather.map((w, index) => {
              return (
                <div key={index} className={styles.readText}>
                  <h3>Current conditions:</h3>
                  <div>{w.description}</div>
                  <div>{w.main}
                    <img
                      width={50}
                      height={50}
                      src={`http://openweathermap.org/img/w/${w.icon}.png`} />
                  </div>
                  <div>Current Temperature: {Math.round(data.main.temp)}&#x2103;</div>
                  <div>Feels Like: {Math.round(data.main.feels_like)}&#x2103;</div>
                  <div>Wind gust: {data.wind.gust}</div>
                </div>
              )
            })

          }
        </div>

        <Link href='/'>
          <button className={styles.buttonStyle}>Back</button>
        </Link>
      </main>
    </>
  )
}



